name: Build all

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Nix
      uses: cachix/install-nix-action@70742d22d932888bb199587f910c72183e62c6da # v6

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build all packages
      run: nix-build
