name: Build all

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Nix
      uses: cachix/install-nix-action@07da2520eebede906fbeefa9dd0a2b635323909d # v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build all packages
      run: nix-build

    - name: Update NUR
      run: curl -XPOST https://nur-update.herokuapp.com/update?repo=dtn7
