name: Update dtn7-go

on: repository_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Nix
      uses: cachix/install-nix-action@70742d22d932888bb199587f910c72183e62c6da # v6

    - name: Checkout
      uses: actions/checkout@v1

    - name: Update dtn7-go packages
      run: ./update-dtn7-go.sh

    - name: Commit and Push
      uses: github-actions-x/commit@310f99bded869e47f73aa47de0955cbc022c4d74 # v2.4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'Updated dtn7-go'
        rebase: true
        name: 'update-dtn7-go.sh'
